name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm i -f
      - name: Run Test Cases
        run: |
          export NODE_OPTIONS="--max-old-space-size=262144"
          npm test
      - name: Build Application
        run: |
          export NODE_OPTIONS="--max-old-space-size=65536"
          npm run build --if-present
      